Feature/ms 006 create interviews logic
estefrare/BaSD-MindSet pull request #11
Opened 2021-11-08 04:01 UTC by ripellizzari

Create the functions: 
-listInterviews
-createInterview
-updateInterview
-removeInterview
Inside the controllers folder, in the interviews.js file.
The JSON file in the data folder
And export every function to the index.js

2021-11-08 12:52 UTC, estefrare requested changes

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +    res.status(201).json(Interviews)
Status 201 is for creations. 
https://developer.mozilla.org/es/docs/Web/HTTP/Status/201

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +const fs = require('fs')
update the file indentation to 2 spaces

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +        }
if you return each `res.status(...` you don't need to use an else condition.

```
if (error) {
  return res.status(400).send(error)
}
return res.status(201).json(deletedSession)
```

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +
REMOVE BREAK LINES

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +        }
if you return each `res.status(...` you don't need to use an else condition.

```
if (error) {
  return res.status(400).send(error)
}
return res.status(201).json(deletedSession)
```

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +    const removeInterview = Interviews.filter(interview => interview.id == req.query.id)
you can use only one filter to do that

```
let removeInterview
const filteredInterview = Interviews.filter((interview) => {
  if(interview.id !== req.query.id) {
    removeInterview = interview
    return false
  }
  return true
})
```

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +    })
if you return each `res.status(...` you don't need to use an else condition.

```
if (error) {
  return res.status(400).send(error)
}
return res.status(201).json(removeInterview)
```

2021-11-08 12:52 UTC, estefrare commented on index.js
> +app.get('/interviews/remove', interviews.removeInterview)
The team decided to use delete instead of remove. 

https://rrcourses.slack.com/archives/C02JCT04R44/p1636301668012900

2021-11-08 12:52 UTC, estefrare commented on data/interviews.json
> +[{"id":312,"idlient":12312312,"idPostulant":12312312312,"idApplication":12312312,"date":"2011-10-05T14:48:00.000Z"},{"id":521,"idClient":12312312,"idPostulant":12312312312,"idApplication":12312312,"d
Format the json file to make it more readable

2021-11-08 12:52 UTC, estefrare commented on controllers/interviews.js
> +    if (removeInterview.length === 0) res.status(404).send('Interview NOT found')
just write `if (!removeInterview.length)` instead of `if (removeInterview.length === 0)`.
0 value means `false`

2021-11-09 01:04 UTC, ravegliamartin approved these changes

2021-11-09 01:58 UTC, leimeterjoaquin approved these changes

2021-11-09 02:16 UTC, estefrare requested changes

2021-11-09 02:16 UTC, estefrare commented on controllers/interviews.js
> +        return res.status(201).send(updatedInterview)
use status code 200. 
201 is for creations

2021-11-09 02:16 UTC, estefrare commented on controllers/interviews.js
> +        return res.status(201).send(removeInterview)
use status code 204 for deletions

2021-11-09 02:16 UTC, estefrare commented on controllers/interviews.js
> +    let removeInterview
the variable should be named `removedInterview`. Verbs are not used for this kind of variable.

Anyway you should use deleted instead of removed

2021-11-09 21:06 UTC, estefrare approved these changes

2021-11-09 23:34 UTC, merged