BaSD-MS-26: Update interviews logic
estefrare/BaSD-MindSet pull request #20
Opened 2021-11-13 06:47 UTC by NicoCagnina

# Interview properties:

| Property  | Type | Required | 
| ------------- | ------------- | ------------- |
| idPostulant | idPostulant | ✔️ |
| idClient | idClient | ✔️ |
| idApplication | idApplication   | ✔️ |
| status | String  | ✔️  |
| date | Date  | ✔️ |
| notes  | String  | ❌ |

### Methods:

- listInterviews
- createInterview
- updateInterview
- deleteInterview

### Status:

- [x] Validations
- [x] Postman colection updated
- [x] Successful interaction with dB
- [ ] Successful interaction with other collections (not enough collections to test)

2021-11-13 12:21 UTC, ignacioaristo requested changes

2021-11-13 12:21 UTC, ignacioaristo commented on controllers/interviews.js
> +
Nico, i think we must use body instead of queries.

2021-11-13 20:21 UTC, estefrare requested changes

2021-11-13 20:21 UTC, estefrare commented on validations/interviews.js
> +  }
also should validate the type of each value

2021-11-13 20:21 UTC, estefrare commented on controllers/interviews.js
> +    application: bodyReq.application,
use `bodyReq` or `req.body` for all cases

2021-11-14 04:04 UTC, estefrare commented
@NicoCagnina remember to delete the `interviews.json` file

2021-11-14 04:13 UTC, estefrare requested changes

2021-11-14 04:13 UTC, estefrare commented on controllers/interviews.js
> +      if (newInterview === null) {
just write `if (!newInterview) {`

2021-11-14 04:13 UTC, estefrare commented on controllers/interviews.js
> +        return res.status(400).json('Interview id does not exist');
status code should be 404

2021-11-14 04:13 UTC, estefrare commented on controllers/interviews.js
> +      return res.status(400).json('Interview id does not exist');
the same as above

2021-11-14 04:13 UTC, estefrare commented on controllers/interviews.js
> +    return res.status(200).json('interview deleted successfully');
204

2021-11-14 04:13 UTC, estefrare commented on models/Interviews.js
> +  },
fix syntax
```
  status: {
    type: String,
    enum: ['succesful', 'failed', 'cancelled', 'assigned', 'confirmed'],
    default: 'assigned',
    required: true,
  },
  ```

2021-11-14 04:13 UTC, estefrare commented on validations/interviews.js
> +  return res.status(200);
why are you sending a response here?

2021-11-14 04:14 UTC, estefrare commented
ESlint error
![image](https://user-images.githubusercontent.com/20587232/141667231-6cf4f6cc-7bc7-4eaf-8437-c8e5556f9b1c.png)

2021-11-14 05:14 UTC, estefrare requested changes

2021-11-14 05:14 UTC, estefrare commented on models/Interviews.js
> +});
add `timestamps: true `

2021-11-14 06:35 UTC, estefrare approved these changes

2021-11-14 13:13 UTC, ignacioaristo approved these changes

2021-11-14 14:45 UTC, merged