BaSD-MS-49: Create applications view
estefrare/BaSD-MindSet pull request #47
Opened 2021-11-22 03:16 UTC by ravegliamartin

## Static Front End Interface 

### Entity: Applications

Functionalities Added:

- List Applications
- Create Applications
- Delete Applications

2021-11-22 04:02 UTC, NicoCagnina commented on public/js/applicationForm.js
> +const dateFormat = (date) => `${[`0${date.getMonth() + 1}`.slice(-2),
Wouldn't it be simpler if you just used the date from the interview?

2021-11-22 04:43 UTC, NicoCagnina commented on public/js/applicationForm.js
> +const dateFormat = (date) => `${[`0${date.getMonth() + 1}`.slice(-2),
Wouldn't it be better if you just used the date from the interview?

2021-11-22 15:46 UTC, estefrare requested changes

2021-11-22 15:46 UTC, estefrare commented on public/js/applicationForm.js
> +fillSelect('/interviews', interviewInput);
You are creating a reusable function but part of the logic is tied to the possible implementations.

```suggestion
const fillSelect = (url, parent, makeText) => {
  fetch(`${window.location.origin}/api${url}`)
    .then((response) => {
      if (response.status !== 200) {
        return response.json().then(({ message }) => {
          throw new Error(message);
        });
      }
      return response.json();
    })
    .then((response) => {
      saveButton.disabled = false;
      response.data.forEach((el) => {
        const option = document.createElement('option');
        // eslint-disable-next-line no-underscore-dangle
        option.value = el._id;
        option.innerText = makeText(el);
        parent.append(option);
      });
    })
    .catch((error) => {
      errorMessage.innerText = error;
    });
};

fillSelect('/positions', positionInput, (el) => `${el.firstName} ${el.lastName}`);
fillSelect('/postulants', postulantInput, (el) => el.jobDescription);
fillSelect('/interviews', interviewInput, (el) => el.date.slice(0, 19).replace('T', ' '));
```

2021-11-22 15:46 UTC, estefrare commented on public/views/applicationForm.html
> +        <select id="interview" name="interview"></select>
see how a date is handled [here](https://github.com/BaSD-2021/Esteban-MindSet-server/pull/45/files#diff-efdbd9ee8c4229255aa369e839207b2f380fec7b405af942426dd30a7bb255f1R23)

2021-11-22 15:46 UTC, estefrare commented on public/js/applicationList.js
> +proceedBtn.onclick = () => {
update variable name based on the button content

2021-11-22 15:46 UTC, estefrare commented on public/js/applicationList.js
> +  window.location.href = `${window.location.origin}/views/applicationForm.html?_id=${id}`;
it is not necessary to use a `_` in the query param name. It is better If you can avoid a lint disable command

2021-11-25 00:09 UTC, estefrare approved these changes

2021-11-25 00:09 UTC, merged